import Head from 'next/head'
// import NavBar from '@/components/Navbar'
// import Used_cars from './home/fetched_cars_divs/used_cars/Used_cars.server'
// import  from './Home/Homepage'
// import { Montserrat } from 'next/font/google'
import Homepage from '@/components/child_components_of_others/home/Homepage'





// const inter = Montserrat({
//   variable: '--font-monteserrat',
// })


export default function Home() {
  return (
    
    <>
      <Head>
        <title>Car Selection</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/whitelogo.png" />
      </Head>
    {/* <NavBar/> */}
    <Homepage/>
    {/* <Used_cars/> */}

    </>
  )
}
