const cities = [
    { cityname: "Karachi", areas: [
      "D.H.A",
      "Gulistan-e-Jauhar",
      "Gulshan-e-Iqbal",
      "Khalid Bin Walid Road",
      "North Nazimabad",
      "Others",
      "Other Areas",
      "A.F.O.H.S",
      "Abdullah Haroon Road",
      "Abul Hassan Isphani Road",
      "Adamjee Nagar",
      "Ahsanabad",
      "Air Port",
      "Aisha Manzil",
      "Al-Hamra Society",
      "Ali Garh Society",
      "Allama Iqbal Town",
      "Amir Khusro",
      "Army Housing",
      "Azizabad",
      "Bagh-e-Korangi",
      "Bahadurabad",
      "Bahria Town Karachi",
      "Baldia Town",
      "Bath Island",
      "Beaumont Road",
      "Bin Qasim Town",
      "Buffer Zone",
      "C.P Berar Society",
      "Cantt",
      "Chapal Skymark",
      "Civil Lines",
      "Clifton",
      "Comissioner Coop Housing Society",
      "Corniche Society",
      "Cotton Export Cooperative Housing Society",
      "D.H.A City",
      "Defence View Society",
      "Dehli Colony",
      "Delhi Colony",
      "DHA Defence",
      "Dhoraji Colony",
      "Faisal Colony",
      "Falaknaz Presidency",
      "Federal B. Area",
      "Frere Town",
      "Gadap Town",
      "Garden",
      "Garden City",
      "Gharo",
      "Gizri",
      "Gizri Road",
      "Gobal Town",
      "Gul Bahar",
      "Gulberg Town",
      "Gulistan e Zafar",
      "Gulistan-e-Hadeed",
      "GULSHAN Block",
      "GULSHAN e sheeraz",
      "Gulshan-e-Iqbal Town",
      "Gulshan-e-Jamal",
      "Gulshan-e-Maymar",
      "Gulshan-e-Mehmood ul Haq",
      "Gulshan-e-Mehran",
      "Gulshan-e-Roomi",
      "Gulshan-e-Tauheed",
      "Gulshan-e-Zahoor",
      "Gulshan_e_Ghazian",
      "Gulzar-e-Hijri",
      "Hawks Bay",
      "Hill Park",
      "Hub River Road",
      "Hussainabad",
      "Hyderabad Colony",
      "I.I. Chundrigar Road",
      "Jamshed Road",
      "Jamshed Town",
      "Javed Bahria Coopretive Housing Society",
      "Jinnah Avenue",
      "Jodi Bazar",
      "Jodia Bazar",
      "K.A.E.C.H.S",
      "Karimabad",
      "Kazimabad",
      "KDA",
      "KDA Scheme 1",
      "Kemari Town",
      "Khayaban-e-Muslim",
      "Kokan Housing Society",
      "Korangi",
      "KPT Officers Society",
      "Lalazar",
      "Landhi",
      "Lasbala Chowk",
      "Lea Market",
      "Liaquat Avenue",
      "Liaquatabad",
      "Lyari Expressway Society",
      "Lyari Town",
      "M.A. Jinnah Road",
      "Malir",
      "Mangopir",
      "Manzoor Colony",
      "Mauripur Road",
      "MDA Scheme 1",
      "Mehmoodabad",
      "Memon Goth",
      "Mithadar",
      "Model Colony",
      "Mohammad Ali Society",
      "Mosa Lane",
      "Nagan Chowrangi",
      "National Highway",
      "Naval Housing Scheme",
      "Navy Housing Scheme",
      "Nawababad",
      "Nazimabad",
      "New Karachi",
      "Nooriabad Industrial Area",
      "North Karachi",
      "Northern Bypass",
      "Old Clifton",
      "Orangi Town",
      "P.E.C.H.S",
      "PAF Housing Scheme",
      "Pakistan Chowk",
      "PIDC",
      "Pir Ahmed Zaman Town",
      "Port Qasim",
      "Punjab Colony",
      "Rafah-e-Aam",
      "Rashid Minhas Road",
      "S.I.T.E",
      "Saadi Road",
      "Saddar",
      "Saddar Town",
      "Safoora",
      "Saforah",
      "Sakhi Hasan",
      "Scheme 33",
      "Scheme 42",
      "Scheme-45",
      "Sea View Apartments",
      "Seven Wonders City",
      "Shadman",
      "Shadman 2",
      "Shah Faisal Colony",
      "Shah Latif Town",
      "Shah Town",
      "Shaheed Millat Road",
      "Shahra-e-Faisal",
      "Shahra-e-Liaquat",
      "Shahra-e-Qaideen",
      "Shahra-e-Usman",
      "Sharfabad",
      "Sharifabad",
      "Sindhi Muslim Society",
      "Soldier Bazar",
      "Steel Town",
      "Sultanabad Society",
      "Super Highway",
      "Surjani Town",
      "Taiser Town",
      "Tariq Road",
      "Teachers Society",
      "Timber Merchants Co-operative Society",
      "Tipu Sultan Road",
      "University Road",
      "Zamzama"
    ]
     },
    { cityname: "Lahore", 
    areas : [
      "Allama Iqbal Town",
      "Cantt",
      "DHA Defence",
      "Gulberg",
      "Johar Town",
      "Others",
      "Other Areas",
      "Aabpara Coop Housing Society",
      "Aashiana Road",
      "Abbot Road",
      "Abdalians Housing Society",
      "Abid Market",
      "Aftab Garden",
      "Agrics Town",
      "Ahbab Housing Society",
      "Air Avenue",
      "AirLine Housing Society",
      "Aitchison Society",
      "Akbar Chowk",
      "Al Ameen Society",
      "Al Faisal Town",
      "Al Hafeez Gardens",
      "Al Hamad Colony",
      "Al Hamra Town",
      "Al Haram Garden",
      "Al Jalil Garden",
      "Al Jannat Housing Scheme",
      "Al Kareem Garden",
      "Al Madina Avenue",
      "Al Noor Town",
      "Al Raheem Town",
      "Al Rahim Homes",
      "Al Rehman Garden",
      "Al-Raheem Garden",
      "Alfalah Town",
      "Ali Town",
      "Ali View Garden",
      "Ali View Park",
      "Allama Iqbal Air Port",
      "Allama Iqbal Intl Airport",
      "Allama Iqbal Road",
      "Alpha Society",
      "Ameen Park",
      "Ameer-ud-Din Park",
      "Anarkali",
      "Anarkali Bazar",
      "Angoori Bagh",
      "Anmol Society",
      "Architects Engineers Housing Society",
      "Army Housing",
      "Ashrafi Town",
      "Asif Town",
      "Askari XI",
      "Askari-X",
      "Atomic Energy Society - PAEC",
      "Audit & Accounts Co-operative Society",
      "Awan Town",
      "Awasia Housing Society",
      "AWT Army Welfare Trust",
      "Ayub Medical Complex",
      "Azam Gardens",
      "Azam Town",
      "Azimabad",
      "Aziz Avenue",
      "Babar Homes",
      "Babu Sabu",
      "Badami Bagh",
      "Bagh-e-Iram Housing Society",
      "Baghban Pura",
      "Bahria Education & Medical City",
      "Bahria Nasheman",
      "Bahria Orchard",
      "Bahria Town",
      "Balkasar",
      "Bankers Avenue",
      "Bankers Cooperative Housing Scheme",
      "Batapur",
      "Beacon House Society",
      "Beadon Road",
      "Bedian Road",
      "Bhatta Chowk",
      "Bilal Gunj",
      "Bilal Town",
      "Bismillah Housing Scheme",
      "BOR Housing Society",
      "Brandreth Road",
      "Bund Road",
      "Burj Attari",
      "Canal Bank Housing Scheme",
      "Canal Bank Road",
      "Canal Burg",
      "Canal Colony",
      "Canal Garden",
      "Canal View",
      "Canalberg Housing Society",
      "Cantt View Society",
      "Cavalry Ground",
      "Central Park Housing Scheme",
      "Chah Miran",
      "Chauburji Park",
      "Chaudhary Colony",
      "Chaudhary Park",
      "China Scheme",
      "Chinar Bagh",
      "Chinar Court",
      "Chungi Amar Sadhu",
      "Circular Road",
      "Civil Defence",
      "Clifton Colony",
      "Cloth Market",
      "COLLEGE ROAD",
      "Cooper Road",
      "Country Homes",
      "Crescent Town",
      "Cricketer Villas",
      "Darogawala",
      "Davis Road",
      "Defence Fort",
      "Defence Road",
      "DHA City",
      "DHA Rehbar",
      "Dharam Pura",
      "Dilkusha Gardens",
      "Divine Gardens",
      "Doctors Housing Society",
      "Dogech",
      "Dream Avenue Lahore",
      "Dream Gardens",
      "Dubai Town",
      "Eden",
      "Eden Avenue",
      "Eden Avenue Extension",
      "Eden Canal Villas",
      "Eden City",
      "Eden Cottage",
      "Eden Park",
      "Eden Place Housing Scheme",
      "Edenabad",
      "Education Town",
      "Egerton Road",
      "Elite Town",
      "EME Society",
      "Empress Road",
      "Excise & Taxation Housing Scheme",
      "Expo Center Near Shaukat Khannam Hospital",
      "Faisal Town",
      "Faisalabad Road",
      "Faisalabad Road",
      "Faiz Bagh",
      "Faiz Pur interchange",
      "Fajar Town",
      "Fane Road",
      "Farooq Colony",
      "Fateh Villas",
      "Fatehabad",
      "Fatehgarh",
      "Fazaia Housing Scheme",
      "Ferozepur Road",
      "Formanites Housing Scheme",
      "Fort Villas",
      "Fotress Stadium",
      "G.T Road",
      "Gaddafi Stadium",
      "Gajju Matah",
      "Garden Town",
      "Garhi Shahu",
      "Gari Shahu",
      "Garrison Model Homes",
      "Gawalmandi",
      "GCP Housing Scheme",
      "Ghausia Colony",
      "Ghazi Road",
      "Ghaziabad",
      "GOR",
      "Gosha-e-Ahbab",
      "Government Employees Cooperative Housing Society (GECHS)",
      "Government Superior Services",
      "Govt Officers Housing Society",
      "Govt. Transport Coop. Housing Society",
      "Grand Avenue Housing Scheme",
      "Green Acres Housing Society",
      "Green Cap Housing Society",
      "Green City",
      "Green Fort",
      "Green Park Society",
      "Green Town",
      "Gujjar Colony",
      "Gujjar Pura",
      "Gul-e-Damin",
      "Gulbahar Colony",
      "Gulbahar Park",
      "Gulberg 2",
      "Guldasht Town",
      "Gulshan Ravi",
      "Gulshan-e-Ahbab",
      "Gulshan-e-Lahore",
      "Gurumangat",
      "Habibullah Colony",
      "Hajvery Housing Scheme",
      "Hall Road",
      "Hamza Town",
      "Harbans Pura",
      "Hassan Town",
      "HBFC Housing Society",
      "Heaven Homes",
      "Highcourt Society",
      "I.E.P Town",
      "IBL Housing Scheme",
      "Ichhra",
      "Icon Valley",
      "IEP Engineers Town",
      "Immad Garden Housing Scheme",
      "Inmol Employees Co-operative Housing Society",
      "Iqbal Avenue",
      "Iqbal Avenue 1",
      "Iqbal Avenue 2",
      "Iqbal Park",
      "Irrigation Colony",
      "Islam Pura",
      "Ittefaq Town",
      "Ittehad Colony",
      "Izmir Town",
      "Jaffar Town",
      "Jaffaria Colony",
      "Jail Road",
      "Jalal Colony",
      "Jallo",
      "Javed Colony",
      "Jhangi",
      "Jinnahabad",
      "Jubilee Town",
      "Jubilee Town",
      "Kacha Jail Road",
      "Kachupura",
      "Kaghan Colony",
      "Kahna",
      "Kakezai Housing Society",
      "Kakul Road",
      "Kala Shah Kaku Interchange",
      "Kamahan Road",
      "Kamra",
      "Karbath",
      "Karim Park",
      "Karimpura Bazar",
      "KEMC Housing Society",
      "Khayaban-e-Amin",
      "Khayaban-e-Jinnah Road",
      "Kot Abdul Malik",
      "Kot Khawaja Saeed",
      "Kot Lakhpat",
      "Kotli Abdur Rahman",
      "Krishan Nagar",
      "L.C.C.H.S",
      "Lahore canal Bank Phase 1",
      "Lahore Cantt Coop Housing",
      "Lahore Medical Housing Society",
      "Lahore Motorway City",
      "Lahore Press Club Housing Scheme",
      "Lake City",
      "Lakhodher",
      "Lakshmi Chowk",
      "Lalazar",
      "Lawrence Road",
      "LDA Avenue",
      "LDA City",
      "Liaquatabad",
      "Liberty Market",
      "Lower Mall",
      "Lower MBuy",
      "Lytton Road",
      "M.M Alam Road",
      "Mahmood Ghaznavi Road",
      "Makkah Colony",
      "Malik Park",
      "Malik Pur",
      "Malipura",
      "Mall Road",
      "Manawan",
      "Mandian",
      "Manga Mandi",
      "Mansehra",
      "Mansoorah",
      "Marghzar Officers Colony",
      "Mason Road",
      "Mateen Avenue",
      "Maulana Shaukat Ali Road",
      "McLeod Road",
      "Mecload Road",
      "Medical Housing Scheme",
      "Mehar Fayaz Colony",
      "Mehmood Booti",
      "Military Accounts",
      "Military Accounts Housing Society",
      "Mirpur",
      "Misri Shah",
      "Model Town",
      "Mohafiz Town",
      "Mohlanwal Scheme",
      "Mominpur",
      "Montgomery Road",
      "Moon Colony",
      "Mozang Chungi",
      "Mughal Pura",
      "Multan Road",
      "Muslim Nagar Housing Scheme",
      "Muslim Town",
      "Mustafa Town",
      "Nadeem Shaheed Road",
      "Nadeem Town",
      "Nadirabad",
      "Nasheman-e-Iqbal",
      "Nasirabad",
      "Nawab Town",
      "Nawaz Sharif Colony",
      "Nayyab Villas",
      "Naz Town",
      "Nazir Garden Society",
      "Nespak Housing Scheme",
      "Nespak Housing Scheme 2",
      "New Choburji Park",
      "New Lahore City",
      "New Muslim Town",
      "New Super Town",
      "NFC",
      "NFC 1",
      "NFC 2",
      "NFC-II",
      "Nisbat Road",
      "Nishter Colony",
      "Officers Colony",
      "Okaf Colony",
      "OPF Housing Scheme",
      "P & D Housing Society",
      "Pace Woodlands",
      "PAF Society",
      "Pak Arab Housing Society",
      "Pakistan Housing Society",
      "Pakistan Medical Housing Society",
      "Palm City",
      "Paragon City",
      "Park View",
      "Park View Villas",
      "PASCO Housing Society",
      "PCSIR Housing Scheme",
      "PCSIR Staff Colony",
      "Pearl Garden Housing Scheme",
      "Peco Road",
      "PIA Housing Scheme",
      "Pine Villas",
      "PMA Road",
      "Public Health Society",
      "Punjab Co-operative Housing Society",
      "Punjab Coop Housing Society",
      "Punjab Govt Employees Society",
      "Punjab Govt Servant Society",
      "Punjab SmBuy Industries Colony",
      "Punjab University Employees Society",
      "Qadri Colony",
      "Qasurpura",
      "Qazi Town",
      "Qilla Gujjar Singh",
      "Quaid-e-Azam Industrial Estate",
      "Quaid-e-Azam Town",
      "Queens Road",
      "Race View",
      "Rail Town",
      "Railway Officers Colony",
      "Raiwind Road",
      "Raj Garh",
      "Rajpoot Town",
      "Rana Town",
      "Rang Mahal",
      "Rasool Park",
      "Ravi Park",
      "Ravi Road",
      "Ravian Society",
      "Real Cottages",
      "Rehman City - Phase 4",
      "Rehman Gardens",
      "Rehman Housing Society",
      "Rehman Villas",
      "Rehmanpura",
      "Revenue Society",
      "Rifle Range Road",
      "River View Coop Housing Society",
      "Riwaz Garden",
      "Rizwan Garden Scheme",
      "Royal Residencia",
      "Sabzazar Scheme",
      "Sadaat Town",
      "Sadat Cooperative Housing Society (College Town)",
      "Sagian",
      "Sagiyan Bridge",
      "Sahafi Colony",
      "Saidpur",
      "Salamatpura",
      "Samanabad",
      "Sanda",
      "Sant Nagar",
      "Saqib Town",
      "SBuyi Town",
      "Shabbir Town",
      "Shadab Garden",
      "Shadbagh",
      "Shadipura",
      "Shadman",
      "Shadman 1",
      "Shadman 2",
      "Shah Jamal",
      "Shah Kamal",
      "Shah Khawar Town",
      "Shahdara",
      "Shahpur Kanjra",
      "Shahtaj Colony",
      "Shahzaman Colony",
      "Shalimar Housing Scheme",
      "Shalimar Link Road",
      "Shalimar Town",
      "Sher Shah Colony",
      "Sheraz Town",
      "Shershah Colony",
      "Sherwanee Town Housing Scheme",
      "Shoukat Town",
      "Siddiqia Colony",
      "Singhpura",
      "Sir Syed Colony",
      "Spring Meadows",
      "State Life Housing Society",
      "Sue-e-Asal",
      "Sui Northern Gas Housing Society",
      "Sukh Chayn Gardens",
      "Sultan Park",
      "Sultan Town",
      "Sundar State",
      "Sunderdas Road",
      "Sunfort Gardens",
      "Sunny Park",
      "Super Town",
      "Supply",
      "Supreme Villas",
      "Swami Nagar",
      "T & T Aabpara Housing Society",
      "Taj Bagh",
      "Taj Pura",
      "Talla Flats",
      "Tariq Gardens",
      "Tauheed Colony",
      "Tech Society",
      "Temple Road",
      "Thokar Niaz Baig",
      "Timber Market",
      "TIP Housing Society",
      "Town Ship",
      "Tricon Village",
      "UET Housing Society",
      "United Bank Officers Cooperative Housing Society",
      "Upper Mall",
      "Urdu Bazar",
      "Valencia Housing Society",
      "Venus Housing Scheme",
      "Vital Homes Housing Scheme",
      "Wafaqi Colony",
      "Wahdat Road",
      "Waheed Brother Colony",
      "Walled City",
      "Walton Railway Officers Colony",
      "Walton Road",
      "Wapda Finance Officers Subsistence Farm Homes Cooperative Society",
      "Wapda Town",
      "Waris Road",
      "Wassanpura",
      "Westwood Housing Society",
      "Younisabad",
      "Zafar Ali Road",
      "Zafar Colony",
      "Zaheer Villas",
      "Zaman Colony",
      "Zaman Park",
      "Zarar Shaheed Road",
    ]
     },
    { cityname: "Islamabad", areas: [] },
    { cityname: "Rawalpindi", areas: [] },
    { cityname: "Peshawar", areas: [] },
    { cityname: "Abbottabad", areas: [] },
    { cityname: "Abdul Hakeem", areas: [] },
    { cityname: "Adda jahan khan", areas: [] },
    { cityname: "Adda shaiwala", areas: [] },
    { cityname: "Ahmed Pur East", areas: [] },
    { cityname: "Ahmedpur Lamma", areas: [] },
    { cityname: "Akora khattak", areas: [] },
    { cityname: "Ali chak", areas: [] },
    { cityname: "Alipur Chatta", areas: [] },
    { cityname: "Allahabad", areas: [] },
    { cityname: "Amangarh", areas: [] },
    { cityname: "Arifwala", areas: [] },
    { cityname: "Attock", areas: [] },
    { cityname: "Babarloi", areas: [] },
    { cityname: "Babri banda", areas: [] },
    { cityname: "Badin", areas: [] },
    { cityname: "Bahawalnagar", areas: [] },
    { cityname: "Bahawalpur", areas: [] },
    { cityname: "Balakot", areas: [] },
    { cityname: "Bannu", areas: [] },
    { cityname: "Baroute", areas: [] },
    { cityname: "Basirpur", areas: [] },
    { cityname: "Basti Shorekot", areas: [] },
    { cityname: "Bat khela", areas: [] },
    { cityname: "Batang", areas: [] },
    { cityname: "Bhai pheru", areas: [] },
    { cityname: "Bhakkar", areas: [] },
    { cityname: "Bhalwal", areas: [] },
    { cityname: "Bhan saeedabad", areas: [] },
    { cityname: "Bhera", areas: [] },
    { cityname: "Bhikky", areas: [] },
    { cityname: "Bhimber", areas: [] },
    { cityname: "Bhirya road", areas: [] },
    { cityname: "Bhuawana", areas: [] },
    { cityname: "Buchay key", areas: [] },
    { cityname: "Buner", areas: [] },
    { cityname: "Burewala", areas: [] },
    { cityname: "Chaininda", areas: [] },
    { cityname: "Chak 4 b c", areas: [] },
    { cityname: "Chak 46", areas: [] },
    { cityname: "Chak jamal", areas: [] },
    { cityname: "Chak jhumra", areas: [] },
    { cityname: "Chak Shahzad", areas: [] },
    { cityname: "Chaklala", areas: [] },
    { cityname: "Chaksawari", areas: [] },
    { cityname: "Chakwal", areas: [] },
    { cityname: "Charsadda", areas: [] },
    { cityname: "Chashma", areas: [] },
    { cityname: "Chawinda", areas: [] },
    { cityname: "Chenab Nagar", areas: [] },
    { cityname: "Chichawatni", areas: [] },
    { cityname: "Chiniot", areas: [] },
    { cityname: "Chishtian", areas: [] },
    { cityname: "Chitral", areas: [] },
    { cityname: "Chohar jamali", areas: [] },
    { cityname: "Choppar hatta", areas: [] },
    { cityname: "Chowha saidan shah", areas: [] },
    { cityname: "Chowk azam", areas: [] },
    { cityname: "Chowk mailta", areas: [] },
    { cityname: "Chowk munda", areas: [] },
    { cityname: "Chunian", areas: [] },
    { cityname: "D.G.Khan", areas: [] },
    { cityname: "Dadakhel", areas: [] },
    { cityname: "Dadu", areas: [] },
    { cityname: "Dadyal Ak", areas: [] },
    { cityname: "Daharki", areas: [] },
    { cityname: "Dandot", areas: [] },
    { cityname: "Dargai", areas: [] },
    { cityname: "Darya khan", areas: [] },
    { cityname: "Daska", areas: [] },
    { cityname: "Daud khel", areas: [] },
    { cityname: "Daulatpur", areas: [] },
    { cityname: "Deh pathan", areas: [] },
    { cityname: "Depal pur", areas: [] },
    { cityname: "Dera Allah Yar", areas: [] },
    { cityname: "Dera ismail khan", areas: [] },
    { cityname: "Dera murad jamali", areas: [] },
    { cityname: "Dera nawab sahib", areas: [] },
    { cityname: "Dhatmal", areas: [] },
    { cityname: "Dhoun kal", areas: [] },
    { cityname: "Digri", areas: [] },
    { cityname: "Dijkot", areas: [] },
    { cityname: "Dina", areas: [] },
    { cityname: "Dinga", areas: [] },
    { cityname: "Dir", areas: [] },
    { cityname: "Doaba", areas: [] },
    { cityname: "Doltala", areas: [] },
    { cityname: "Domeli", areas: [] },
    { cityname: "Donga Bonga", areas: [] },
    { cityname: "Dudial", areas: [] },
    { cityname: "Dunia Pur", areas: [] },
    { cityname: "Eminabad", areas: [] },
    { cityname: "Esa Khel", areas: [] },
    { cityname: "Faisalabad", areas: [] },
    { cityname: "Faqirwali", areas: [] },
    { cityname: "Farooqabad", areas: [] },
    { cityname: "Fateh Jang", areas: [] },
    { cityname: "Fateh pur", areas: [] },
    { cityname: "Feroz walla", areas: [] },
    { cityname: "Feroz watan", areas: [] },
    { cityname: "Feroz Watwan", areas: [] },
    { cityname: "Fiza got", areas: [] },
    { cityname: "Fort Abbass", areas: [] },
    { cityname: "Gadoon amazai", areas: [] },
    { cityname: "Gaggo mandi", areas: [] },
    { cityname: "Gakhar mandi", areas: [] },
    { cityname: "Gambat", areas: [] },
    { cityname: "Gambet", areas: [] },
    { cityname: "Garh maharaja", areas: [] },
    { cityname: "Garh more", areas: [] },
    { cityname: "Garhi yaseen", areas: [] },
    { cityname: "Gari habibullah", areas: [] },
    { cityname: "Gari mori", areas: [] },
    { cityname: "Gharo", areas: [] },
    { cityname: "Ghazi", areas: [] },
    { cityname: "Ghotki", areas: [] },
    { cityname: "Gilgit", areas: [] },
    { cityname: "Gohar ghoushti", areas: [] },
    { cityname: "Gojra", areas: [] },
    { cityname: "Goth Machi", areas: [] },
    { cityname: "Goular khel", areas: [] },
    { cityname: "Guddu", areas: [] },
    { cityname: "Gujar Khan", areas: [] },
    { cityname: "Gujar khan", areas: [] },
    { cityname: "Gujranwala", areas: [] },
    { cityname: "Gujrat", areas: [] },
    { cityname: "Gwadar", areas: [] },
    { cityname: "Hafizabad", areas: [] },
    { cityname: "Hala", areas: [] },
    { cityname: "Hangu", areas: [] },
    { cityname: "Harappa", areas: [] },
    { cityname: "Haripur", areas: [] },
    { cityname: "Hariwala", areas: [] },
    { cityname: "Haroonabad", areas: [] },
    { cityname: "Hasilpur", areas: [] },
    { cityname: "Hassan abdal", areas: [] },
    { cityname: "Hattar", areas: [] },
    { cityname: "Hattian", areas: [] },
    { cityname: "Hattian lawrencepur", areas: [] },
    { cityname: "Havali Lakhan", areas: [] },
    { cityname: "Hawilian", areas: [] },
    { cityname: "Hayatabad", areas: [] },
    { cityname: "Hazro", areas: [] },
    { cityname: "Head marala", areas: [] },
    { cityname: "Hub", areas: [] },
    { cityname: "Hub-Balochistan", areas: [] },
    { cityname: "Hujra Shah Mukeem", areas: [] },
    { cityname: "Hunza", areas: [] },
    { cityname: "Hyderabad", areas: [] },
    { cityname: "Iskandarabad", areas: [] },
    { cityname: "Jacobabad", areas: [] },
    { cityname: "Jahaniya", areas: [] },
    { cityname: "Jaja abasian", areas: [] },
    { cityname: "Jalalpur Jattan", areas: [] },
    { cityname: "Jalalpur Pirwala", areas: [] },
    { cityname: "Jampur", areas: [] },
    { cityname: "Jamrud road", areas: [] },
    { cityname: "Jamshoro", areas: [] },
    { cityname: "Jan pur", areas: [] },
    { cityname: "Jand", areas: [] },
    { cityname: "Jandanwala", areas: [] },
    { cityname: "Jaranwala", areas: [] },
    { cityname: "Jatlaan", areas: [] },
    { cityname: "Jatoi", areas: [] },
    { cityname: "Jauharabad", areas: [] },
    { cityname: "Jehangira", areas: [] },
    { cityname: "Jhal Magsi", areas: [] },
    { cityname: "Jhand", areas: [] },
    { cityname: "Jhang", areas: [] },
    { cityname: "Jhatta bhutta", areas: [] },
    { cityname: "Jhelum", areas: [] },
    { cityname: "Jhudo", areas: [] },
    { cityname: "Jin Pur", areas: [] },
    { cityname: "K.N. Shah", areas: [] },
    { cityname: "Kabirwala", areas: [] },
    { cityname: "Kacha khooh", areas: [] },
    { cityname: "Kahuta", areas: [] },
    { cityname: "Kakul", areas: [] },
    { cityname: "Kakur town", areas: [] },
    { cityname: "Kala bagh", areas: [] },
    { cityname: "Kala shah kaku", areas: [] },
    { cityname: "Kalaswala", areas: [] },
    { cityname: "Kallar Kahar", areas: [] },
    { cityname: "Kallar Saddiyian", areas: [] },
    { cityname: "Kallur kot", areas: [] },
    { cityname: "Kamalia", areas: [] },
    { cityname: "Kamalia musa", areas: [] },
    { cityname: "Kamber ali khan", areas: [] },
    { cityname: "Kameer", areas: [] },
    { cityname: "Kamoke", areas: [] },
    { cityname: "Kamra", areas: [] },
    { cityname: "Kandh kot", areas: [] },
    { cityname: "Kandiaro", areas: [] },
    { cityname: "Karak", areas: [] },
    { cityname: "Karoor pacca", areas: [] },
    { cityname: "Karore lalisan", areas: [] },
    { cityname: "Kashmir", areas: [] },
    { cityname: "Kashmore", areas: [] },
    { cityname: "Kasur", areas: [] },
    { cityname: "Kazi ahmed", areas: [] },
    { cityname: "Khairpur", areas: [] },
    { cityname: "Khairpur Mir", areas: [] },
    { cityname: "Khan Bela", areas: [] },
    { cityname: "Khan qah sharif", areas: [] },
    { cityname: "Khandabad", areas: [] },
    { cityname: "Khanewal", areas: [] },
    { cityname: "Khangarh", areas: [] },
    { cityname: "Khanpur", areas: [] },
    { cityname: "Khanqah dogran", areas: [] },
    { cityname: "Khanqah sharif", areas: [] },
    { cityname: "Kharian", areas: [] },
    { cityname: "Khewra", areas: [] },
    { cityname: "Khoski", areas: [] },
    { cityname: "Khudian Khas", areas: [] },
    { cityname: "Khurian wala", areas: [] },
    { cityname: "Khurrianwala", areas: [] },
    { cityname: "Khushab", areas: [] },
    { cityname: "Khushal kot", areas: [] },
    { cityname: "Khuzdar", areas: [] },
    { cityname: "Khyber", areas: [] },
    { cityname: "Klaske", areas: [] },
    { cityname: "Kohat", areas: [] },
    { cityname: "Kot addu", areas: [] },
    { cityname: "Kot bunglow", areas: [] },
    { cityname: "Kot ghulam mohd", areas: [] },
    { cityname: "Kot mithan", areas: [] },
    { cityname: "Kot Momin", areas: [] },
    { cityname: "Kot radha kishan", areas: [] },
    { cityname: "Kotla", areas: [] },
    { cityname: "Kotla arab ali khan", areas: [] },
    { cityname: "Kotla jam", areas: [] },
    { cityname: "Kotla Pathan", areas: [] },
    { cityname: "Kotli Ak", areas: [] },
    { cityname: "Kotli Loharan", areas: [] },
    { cityname: "Kotri", areas: [] },
    { cityname: "Kumbh", areas: [] },
    { cityname: "Kundina", areas: [] },
    { cityname: "Kunjah", areas: [] },
    { cityname: "Kunri", areas: [] },
    { cityname: "Lakki marwat", areas: [] },
    { cityname: "Lala musa", areas: [] },
    { cityname: "Lala rukh", areas: [] },
    { cityname: "Laliah", areas: [] },
    { cityname: "Lalshanra", areas: [] },
    { cityname: "Larkana", areas: [] },
    { cityname: "Lasbela", areas: [] },
    { cityname: "Lawrence pur", areas: [] },
    { cityname: "Layyah", areas: [] },
    { cityname: "Liaqat Pur", areas: [] },
    { cityname: "Lodhran", areas: [] },
    { cityname: "Lower Dir", areas: [] },
    { cityname: "Ludhan", areas: [] },
    { cityname: "Makli", areas: [] },
    { cityname: "Malakand Agency", areas: [] },
    { cityname: "Malakwal", areas: [] },
    { cityname: "Mamu kunjan", areas: [] },
    { cityname: "Mandi bahauddin", areas: [] },
    { cityname: "Mandra", areas: [] },
    { cityname: "Manga mandi", areas: [] },
    { cityname: "Mangal sada", areas: [] },
    { cityname: "Mangi", areas: [] },
    { cityname: "Mangla", areas: [] },
    { cityname: "Mangowal", areas: [] },
    { cityname: "Manoabad", areas: [] },
    { cityname: "Mansehra", areas: [] },
    { cityname: "Mardan", areas: [] },
    { cityname: "Mari indus", areas: [] },
    { cityname: "Mastoi", areas: [] },
    { cityname: "Matli", areas: [] },
    { cityname: "Mehar", areas: [] },
    { cityname: "Mehmood kot", areas: [] },
    { cityname: "Mehrabpur", areas: [] },
    { cityname: "Melsi", areas: [] },
    { cityname: "Mian Channu", areas: [] },
    { cityname: "Mian Wali", areas: [] },
    { cityname: "Minchanabad", areas: [] },
    { cityname: "Mingora", areas: [] },
    { cityname: "Mir ali", areas: [] },
    { cityname: "Miran shah", areas: [] },
    { cityname: "Mirpur A.K.", areas: [] },
    { cityname: "Mirpur khas", areas: [] },
    { cityname: "Mirpur mathelo", areas: [] },
    { cityname: "Mithi", areas: [] },
    { cityname: "Mitiari", areas: [] },
    { cityname: "Mohen jo daro", areas: [] },
    { cityname: "More kunda", areas: [] },
    { cityname: "Morgah", areas: [] },
    { cityname: "Moro", areas: [] },
    { cityname: "Mubarik pur", areas: [] },
    { cityname: "Multan", areas: [] },
    { cityname: "Muridke", areas: [] },
    { cityname: "Murree", areas: [] },
    { cityname: "Musafir khana", areas: [] },
    { cityname: "Mustung", areas: [] },
    { cityname: "Muzaffar Gargh", areas: [] },
    { cityname: "Muzaffarabad", areas: [] },
    { cityname: "Nankana sahib", areas: [] },
    { cityname: "Narang mandi", areas: [] },
    { cityname: "Narowal", areas: [] },
    { cityname: "Naseerabad", areas: [] },
    { cityname: "Naukot", areas: [] },
    { cityname: "Naukundi", areas: [] },
    { cityname: "Nawabshah", areas: [] },
    { cityname: "New saeedabad", areas: [] },
    { cityname: "Nilore", areas: [] },
    { cityname: "Noor kot", areas: [] },
    { cityname: "Nooriabad", areas: [] },
    { cityname: "Noorpur nooranga", areas: [] },
    { cityname: "Noshero Feroze", areas: [] },
    { cityname: "Noudero", areas: [] },
    { cityname: "Nowshera", areas: [] },
    { cityname: "Nowshera cantt", areas: [] },
    { cityname: "Nowshera Virka", areas: [] },
    { cityname: "Okara", areas: [] },
    { cityname: "Other", areas: [] },
    { cityname: "Padidan", areas: [] },
    { cityname: "Pak china fertilizer", areas: [] },
    { cityname: "Pak pattan sharif", areas: [] },
    { cityname: "Panjan kisan", areas: [] },
    { cityname: "Panjgoor", areas: [] },
    { cityname: "Pano Aqil", areas: [] },
    { cityname: "Pano Aqil", areas: [] },
    { cityname: "Pasni", areas: [] },
    { cityname: "Pasrur", areas: [] },
    { cityname: "Pattoki", areas: [] },
    { cityname: "Phagwar", areas: [] },
    { cityname: "Phalia", areas: [] },
    { cityname: "Phool nagar", areas: [] },
    { cityname: "Piaro goth", areas: [] },
    { cityname: "Pind Dadan Khan", areas: [] },
    { cityname: "Pindi Bhattian", areas: [] },
    { cityname: "Pindi bohri", areas: [] },
    { cityname: "Pindi gheb", areas: [] },
    { cityname: "Piplan", areas: [] },
    { cityname: "Pir mahal", areas: [] },
    { cityname: "Pishin", areas: [] },
    { cityname: "Qalandarabad", areas: [] },
    { cityname: "Qamber Ali Khan", areas: [] },
    { cityname: "Qasba gujrat", areas: [] },
    { cityname: "Qazi ahmed", areas: [] },
    { cityname: "Qila Deedar Singh", areas: [] },
    { cityname: "Quaid Abad", areas: [] },
    { cityname: "Quetta", areas: [] },
    { cityname: "Rahim Yar Khan", areas: [] },
    { cityname: "Rahwali", areas: [] },
    { cityname: "Raiwind", areas: [] },
    { cityname: "Rajana", areas: [] },
    { cityname: "Rajanpur", areas: [] },
    { cityname: "Rangoo", areas: [] },
    { cityname: "Ranipur", areas: [] },
    { cityname: "Rato Dero", areas: [] },
    { cityname: "Rawalakot", areas: [] },
    { cityname: "Rawat", areas: [] },
    { cityname: "Renala khurd", areas: [] },
    { cityname: "Risalpur", areas: [] },
    { cityname: "Rohri", areas: [] },
    { cityname: "Sadiqabad", areas: [] },
    { cityname: "Sagri", areas: [] },
    { cityname: "Sahiwal", areas: [] },
    { cityname: "Saidu sharif", areas: [] },
    { cityname: "Sajawal", areas: [] },
    { cityname: "Sakhi Sarwar", areas: [] },
    { cityname: "Samanabad", areas: [] },
    { cityname: "Sambrial", areas: [] },
    { cityname: "Samma satta", areas: [] },
    { cityname: "Sanghar", areas: [] },
    { cityname: "Sanghi", areas: [] },
    { cityname: "Sangla Hills", areas: [] },
    { cityname: "Sangote", areas: [] },
    { cityname: "Sanjarpur", areas: [] },
    { cityname: "Sanjwal", areas: [] },
    { cityname: "Sara e naurang", areas: [] },
    { cityname: "Sara-E-Alamgir", areas: [] },
    { cityname: "Sarai alamgir", areas: [] },
    { cityname: "Sargodha", areas: [] },
    { cityname: "Satiana", areas: [] },
    { cityname: "Sehar baqlas", areas: [] },
    { cityname: "Sehwan Sharif", areas: [] },
    { cityname: "Sekhat", areas: [] },
    { cityname: "Shadiwal", areas: [] },
    { cityname: "Shah kot", areas: [] },
    { cityname: "Shahdad kot", areas: [] },
    { cityname: "Shahdadpur", areas: [] },
    { cityname: "Shahdara", areas: [] },
    { cityname: "Shahpur", areas: [] },
    { cityname: "Shahpur Chakar", areas: [] },
    { cityname: "Shahpur Saddar", areas: [] },
    { cityname: "Shakargarh", areas: [] },
    { cityname: "Shamsabad", areas: [] },
    { cityname: "Shankiari", areas: [] },
    { cityname: "Shedani sharif", areas: [] },
    { cityname: "Shehdadpur", areas: [] },
    { cityname: "Sheikhupura", areas: [] },
    { cityname: "Shemier", areas: [] },
    { cityname: "Shikar pur", areas: [] },
    { cityname: "Shorkot", areas: [] },
    { cityname: "Shuja abad", areas: [] },
    { cityname: "Sialkot", areas: [] },
    { cityname: "Sibi", areas: [] },
    { cityname: "Sihala", areas: [] },
    { cityname: "Sikandarabad", areas: [] },
    { cityname: "Sillanwali", areas: [] },
    { cityname: "Sinawan", areas: [] },
    { cityname: "Sita road", areas: [] },
    { cityname: "Skardu", areas: [] },
    { cityname: "Sohawa", areas: [] },
    { cityname: "Sohawa district daska", areas: [] },
    { cityname: "Sukkur", areas: [] },
    { cityname: "Sumandari", areas: [] },
    { cityname: "Swabi", areas: [] },
    { cityname: "Swat", areas: [] },
    { cityname: "Swatmingora", areas: [] },
    { cityname: "Takhtbai", areas: [] },
    { cityname: "Talagang", areas: [] },
    { cityname: "Talamba", areas: [] },
    { cityname: "Talhur", areas: [] },
    { cityname: "Tandiliyawala", areas: [] },
    { cityname: "Tando adam", areas: [] },
    { cityname: "Tando allah yar", areas: [] },
    { cityname: "Tando jam", areas: [] },
    { cityname: "Tando mohd khan", areas: [] },
    { cityname: "Tangi", areas: [] },
    { cityname: "Tank", areas: [] },
    { cityname: "Tarbela", areas: [] },
    { cityname: "Tarmatan", areas: [] },
    { cityname: "Taunsa sharif", areas: [] },
    { cityname: "Taxila", areas: [] },
    { cityname: "Tharo Shah", areas: [] },
    { cityname: "Thatta", areas: [] },
    { cityname: "Theing jattan more", areas: [] },
    { cityname: "Thull", areas: [] },
    { cityname: "Tibba sultanpur", areas: [] },
    { cityname: "Toba Tek Singh", areas: [] },
    { cityname: "Topi", areas: [] },
    { cityname: "Toru", areas: [] },
    { cityname: "Tranda Muhammad Pannah", areas: [] },
    { cityname: "Turbat", areas: [] },
    { cityname: "Ubaro", areas: [] },
    { cityname: "Ubauro", areas: [] },
    { cityname: "Ugoke", areas: [] },
    { cityname: "Ukba", areas: [] },
    { cityname: "Umarao", areas: [] },
    { cityname: "Umer Kot", areas: [] },
    { cityname: "Upper deval", areas: [] },
    { cityname: "Usta mohammad", areas: [] },
    { cityname: "Vehari", areas: [] },
    { cityname: "Village Sunder", areas: [] },
    { cityname: "Wah cantt", areas: [] },
    { cityname: "Wahi hassain", areas: [] },
    { cityname: "Wahn Bachran", areas: [] },
    { cityname: "Wan radha ram", areas: [] },
    { cityname: "Warah", areas: [] },
    { cityname: "Warburton", areas: [] },
    { cityname: "Wazirabad", areas: [] },
    { cityname: "Yazman mandi", areas: [] },
    { cityname: "Zahir Pir", areas: [] },
    { cityname: "Zaida", areas: [] },
    { cityname: "Zhob", areas: [] }
  ];


  export default cities;