const colors = [
    { colorname: 'White', colorcode: '#FFFFFF' },
    { colorname: 'Silver', colorcode: '#C0C0C0' },
    { colorname: 'Black', colorcode: '#000000' },
    { colorname: 'Grey', colorcode: '#808080' },
    { colorname: 'Blue', colorcode: '#0000FF' },
    { colorname: 'Green', colorcode: '#008000' },
    { colorname: 'Red', colorcode: '#FF0000' },
    { colorname: 'Gold', colorcode: '#FFD700' },
    { colorname: 'Maroon', colorcode: '#800000' },
    { colorname: 'Beige', colorcode: '#F5F5DC' },
    { colorname: 'Pink', colorcode: '#FFC0CB' },
    { colorname: 'Brown', colorcode: '#A52A2A' },
    { colorname: 'Burgundy', colorcode: '#800020' },
    { colorname: 'Yellow', colorcode: '#FFFF00' },
    { colorname: 'Bronze', colorcode: '#CD7F32' },
    { colorname: 'Purple', colorcode: '#800080' },
    { colorname: 'Turquoise', colorcode: '#40E0D0' },
    { colorname: 'Orange', colorcode: '#FFA500' },
    { colorname: 'Indigo', colorcode: '#4B0082' },
    { colorname: 'Magenta', colorcode: '#FF00FF' },
    { colorname: 'Navy', colorcode: '#000080' },
    { colorname: 'unlisted', colorcode: '#0000' },
  ];

  export default colors;